# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UldkGugik
                                 A QGIS plugin
 Wtyczka pozwala na pobieranie geometrii granic działek katastralnych, obrębów, gmin, powiatów i województw.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-31
        copyright            : (C) 2019 by Michał Włoga - Envirosolutions Sp. z o.o.
        email                : office@envirosolutions.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

PLUGIN_VERSION = ''
PLUGIN_NAME = ''

plugin_libs_path = os.path.join(os.path.dirname(__file__), 'libs')
if os.path.isdir(plugin_libs_path):
    for file in os.listdir(plugin_libs_path):
        if file.endswith('.whl'):
            sys.path.append(os.path.join(plugin_libs_path, file))

metadata_path = os.path.join(os.path.dirname(__file__), 'metadata.txt')
with open(metadata_path, 'r', encoding='utf-8') as pluginMetadataFile:
    for line in pluginMetadataFile.readlines():
        if line.startswith("version="):
            PLUGIN_VERSION = line.strip().split('=', 1)[-1]
        if line.startswith("name="):
            PLUGIN_NAME = line.strip().split('=', 1)[-1]

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UldkGugik class from file UldkGugik.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .uldk_gugik import UldkGugik
    return UldkGugik(iface)
